---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  # AWS integration for Secrets Manager (optional)
  - name: amazon.aws
    version: ">=7.0.0"

  # Community general modules
  - name: community.general
    version: ">=8.0.0"

  # Jeff Geerling's macOS collection (includes homebrew, dock roles)
  - name: geerlingguy.mac
    version: ">=5.0.0"
