---
# Inventory file for build machines
# For ansible-pull mode, this is mainly for documentation
# Each machine runs playbooks locally against itself

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  children:
    build_machines:
      hosts:
        # Add your build machines here for push-mode or inventory tracking
        # build-mac-01:
        #   ansible_host: 192.168.1.101
        # build-mac-02:
        #   ansible_host: 192.168.1.102
